services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: capublic
      POSTGRES_USER: capublic
      POSTGRES_PASSWORD: capublic
    volumes:
      - pgdata:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"

volumes:
  pgdata:
